homebrew_packages:
  - ansible
  - asciinema
  - bash-completion
  - ccat
  - ccrypt
  - curl
  - direnv
  - fd
  - fish
  - fzf
  - gh
  - git
  - hey
  - highlight
  - httpie
  - helm
  - hyper
  - iterm
  - jenv
  - jq
  - kind
  - kube-ps1
  - kubernetes-cli
  - kubectx
  - minikube
  - nmap
  - openshift-cli
  - pandoc
  - pass
  - pssh
  - pipenv
  - pv
  - pwgen
  - pyenv
  - python3
  - starship
  - terminus
  - terraform
  - tmux
  - tmuxinator
  - tree
  - wget
  - watch
  - vault
  - xz
  - yq
  - zsh
  - zsh-abbr
  - zsh-completions
  - zsh-autosuggestions
  - zsh-syntax-highlighting


homebrew_cask_packages:
  - iterm2
  - postman
  - dracula-terminal
  
# brew tap dracula/install
# brew install --cask dracula-terminal

