homebrew_packages:
  - curl
  - direnv
  - fd
  - fish
  - git
  - hey
  - highlight
  - httpie
  - hyper
  - iterm
  - jenv
  - jq
  - kind
  - kube-ps1
  - kubectx
  - minikube
  - pass
  - pssh
  - pyenv
  - python3
  - terminus
  - terraform
  - tmux
  - tmuxinator
  - tree
  - wget
  - xz
  - zsh
  - zsh-abbr
  - zsh-completions
  - zsh-syntax-highlighting


homebrew_cask_packages:
  - iterm2
  - postman
