homebrew_packages:
  - curl
  - python3
  - git
  - direnv
  - wget
  - pyenv
  - httpie
  - fd
  - fish
  - jenv
  - jq
  - kind
  - kube-ps1
  - kubectx
  - pssh
  - tmux
  - terraform
  - tmuxinator
  - tree
  - xz
  - zsh
  - zsh-abbr
  - zsh-completions
  - iterm
  - hyper
  - terminus

homebrew_cask_packages:
  - iterm2
