- name: Setup Mac
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - config.yml
  tasks:
    - name: Upgrade all homebrew packages
      homebrew:
        update_homebrew: yes
        upgrade_all: yes

    - name: Install Homebrew Packages
      homebrew:
        state: present
      loop: "{{ homebrew_packages }}"

    - name: cleanup Brew
      shell: brew cleanup

    - name: Install Python
      shell: pyenv install -s 3.9.4

    - name: Upgrade Pip
      shell: python -m pip install --upgrade pip

    - name: Install AWS CLI
      pip:
        name: awscli
